### ISSUE TITLE
Nested messages don't generate the TS definitions

### ISSUE THREAD

**Issue by jonathaningram** [larrymyers/protoc-gen-twirp_typescript#1]
Take this service.proto:

```proto
syntax = "proto3";

package twitch.twirp.example;
option go_package = "example";

import "google/protobuf/timestamp.proto";

// A Hat is a piece of headwear made by a Haberdasher.
message Hat {
    // The size of a hat should always be in inches.
    int32 size = 1;

    // The color of a hat will never be 'invisible', but other than
    // that, anything is fair game.
    string color = 2;

    // The name of a hat is it's type. Like, 'bowler', or something.
    string name = 3;

    google.protobuf.Timestamp created_on = 4;

    message Nested {
        string a = 1;
        string b = 2;
    }

    Nested nested = 5;
}

// Size is passed when requesting a new hat to be made. It's always
// measured in inches.
message Size {
    int32 inches = 1;
}

// A Haberdasher makes hats for clients.
service Haberdasher {
    // MakeHat produces a hat of mysterious, randomly-selected color!
    rpc MakeHat(Size) returns (Hat);
}
```

The TS that is output is:

```ts

import {createTwirpRequest, throwTwirpError, Fetch} from './twirp';


export interface Hat {
    size: number;
    color: string;
    name: string;
    createdOn: Date;
    nested: Nested;
    
}

interface HatJSON {
    size: number;
    color: string;
    name: string;
    created_on: string;
    nested: NestedJSON;
    
}

const HatToJSON = (m: Hat): HatJSON => {
    return {
        size: m.size,
        color: m.color,
        name: m.name,
        created_on: m.createdOn.toISOString(),
        nested: NestedToJSON(m.nested),
        
    };
};

const JSONToHat = (m: HatJSON): Hat => {
    return {
        size: m.size,
        color: m.color,
        name: m.name,
        createdOn: new Date(m.created_on),
        nested: JSONToNested(m.nested),
        
    };
};

export interface Size {
    inches: number;
    
}

interface SizeJSON {
    inches: number;
    
}

const SizeToJSON = (m: Size): SizeJSON => {
    return {
        inches: m.inches,
        
    };
};

const JSONToSize = (m: SizeJSON): Size => {
    return {
        inches: m.inches,
        
    };
};



export interface Haberdasher {
    makeHat: (size: Size) => Promise<Hat>;
    
}

export class DefaultHaberdasher implements Haberdasher {
    private hostname: string;
    private fetch: Fetch;
    private pathPrefix = "/twirp/twitch.twirp.example.Haberdasher/";

    constructor(hostname: string, fetch: Fetch) {
        this.hostname = hostname;
        this.fetch = fetch;
    }
    makeHat(size: Size): Promise<Hat> {
        const url = this.hostname + this.pathPrefix + "MakeHat";
        return this.fetch(createTwirpRequest(url, SizeToJSON(size))).then((resp) => {
            if (!resp.ok) {
                return throwTwirpError(resp);
            }

            return resp.json().then(JSONToHat);
        });
    }
    
}
```

You can see that `Nested` and friends is not generated.

I haven't yet had a look at your implementation to take a go at a PR, but wanted to report this in the meantime.

**Comment by jonathaningram** [comment]
So we need to essentially recurse on all nested types here: 

https://github.com/larrymyers/protoc-gen-twirp_typescript/blob/master/generator/client.go#L117

It might be worth some discussion as to how this should work. E.g. should the nested type be named `Hat_Nested` (as protoc would generate for service.pb.go) or should it use some TS namespaces or some such thing?

**Comment by larrymyers** [comment]
@jonathaningram I took at look at what protobufjs does: https://github.com/dcodeIO/ProtoBuf.js/#pbts-for-typescript

It uses typescript namespaces to declare nested messages.

**Comment by larrymyers** [comment]
@jonathaningram I think with an adapter library ProtoBuf.js would be suitable for twirp.  It provides a transport agostic RPC layer, though the API for it isn't the most straightforward from what I've seen.

My main reasons for writing my own client generator were:

* Produce idiomatic Typescript that is easy to read and integrate into existing projects.
* Generate a service layer that is easy to use in unit tests.
* Use json instead of protobufs to minimize the overhead in browser usage and keep debugging easy.

If you look at one of the original issues I filed over on the twirp project:

https://github.com/twitchtv/twirp/issues/84

You can see some of the debate around json vs protobuf as a message format in the browser.

**Comment by jonathaningram** [comment]
@larrymyers I noticed you started work on nested messages. Were you planning to continue with it or did you want me to have a go at a PR?

**Comment by larrymyers** [comment]
@jonathaningram Go ahead and take this on if you have the time. I've stalled on this bug.

**Comment by jonathaningram** [comment]
@larrymyers will try and give it a go.
