### ISSUE TITLE
Repated message inside of repeated message throws an error

### ISSUE THREAD

**Issue by aneshas** [larrymyers/protoc-gen-twirp_typescript#11]
Hey, nice plugin, but we found a following issue while using it:

```protobuf
message A {
  repeated B b = 1;
}

message B {
  repeated C c = 1;
}

message C { ... }
```

throws an error for `repeated C c =1` - (second level of repeated nesting)

**Comment by ribice** [comment]
Still having issues with this. Any update @larrymyers?

**Comment by larrymyers** [comment]
@ribice I'm not actively working to resolve this issue right now. I'd happily welcome a pull request to resolve it.  An alternative for more complete protobuf spec parsing would be to use https://github.com/dcodeIO/protobuf.js with a twirp adapter. I've successfully done this in a branch, but have yet to integrate it back into master.
