### ISSUE TITLE
Default output format does not match spec.

### ISSUE THREAD

**Issue by keynan** [larrymyers/protoc-gen-twirp_typescript#12]
Per the documentation here https://developers.google.com/protocol-buffers/docs/proto3#json

```
Use proto field name instead of lowerCamelCase name: By default proto3 JSON printer should convert the field name to lowerCamelCase and use that as the JSON name. An implementation may provide an option to use proto field name as the JSON name instead. Proto3 JSON parsers are required to accept both the converted lowerCamelCase name and the proto field name.
```

The exposed typescript is converted to the correct casing but the __JSON variant used in serialisation uses the explicit name in protobuf. Interop with other languages / generated has made this a bit of a linch pin.

**Comment by larrymyers** [comment]
@keynan Does this work with twirp? I remember when I wrote this initially that twirp does not support lowerCamelCase JSON at all.

**Comment by keynan** [comment]
If you mean the spec, yes. The implementation for go? not sure, still setting up the pact test for that one. It does work with the javax implementation.

In either case it's backwards compatible. You only get LCC if you set that boolean flag. And since it should now be able to parse both should be resistant to bad behaviour in other implementations.

**Comment by larrymyers** [comment]
merged.
