### ISSUE TITLE
Allow configurable pathPrefix

### ISSUE THREAD

**Issue by rynop** [larrymyers/protoc-gen-twirp_typescript#19]
1st off THANK YOU for this.  I want to give you a hug cuz I've been debating for about a week on starting a Protobuf.js implementation and just noticed you pushed it 2 days ago!

You may already know that the https://github.com/twitchtv/twirp/tree/v6_prerelease branch no longer has the `/twirp` path prefix by default.

Do you think its possible to make this configurable in your generator? Ex: https://github.com/larrymyers/protoc-gen-twirp_typescript/blob/master/example/ts_client/service.ts#L60 would optionally not contain `/twirp`

Ultimately you'd run something like this (I use [retool](https://github.com/twitchtv/retool)):

```
retool add github.com/golang/protobuf/protoc-gen-go origin/master
retool add github.com/twitchtv/twirp/protoc-gen-twirp origin/v6_prerelease
retool add github.com/larrymyers/protoc-gen-twirp_typescript/tree/master/generator origin/master
retool do protoc --twirp_typescript_out=path_prefix=:./example/ts_client ./example/service.proto
```

I've never written protoc plugin before so syntax is prob way off, just trying to convey idea...

**Comment by larrymyers** [comment]
is v6 released yet? I'd say once v6 is officially released it'd be a valuable addition to this library.

**Comment by rynop** [comment]
No but its been in progress for a [long time](https://github.com/twitchtv/twirp/pull/112), so folks have been [using it in production](https://github.com/twitchtv/twirp/issues/55#issuecomment-365755250)

I'm fine waiting til v6 GA.  FWIW when v6 GAs you'll have a situation where you'll need to support both prefix/no-prefix/custom prefix

**Comment by larrymyers** [comment]
Okay, a custom path prefix should be pretty straight forward if provided as another cli arg when executing proton.  I'll mark this as a feature request.

**Comment by larrymyers** [comment]
@rynop If you update to the latest master you'll be able to use Twirp v6.  I tested both generators in the example project and it works as expected.  Note this is just the path routing portion, to the best of my knowledge features like streaming support haven't landed yet.

**Comment by rynop** [comment]
Thank for this.  I think there is something going on with your go.larrymyers.com not tracking `master`.  The following is still installing the `5f59d5a` commit.

```
go get -u go.larrymyers.com/protoc-gen-twirp_typescript
```

I use [retool](https://github.com/twitchtv/retool) to vendor my tools, it is much more explicit on git commit hash tracking.  It also confirms what I'm seeing with `go get`

```
retool add go.larrymyers.com/protoc-gen-twirp_typescript origin/master

grep protoc-gen-twirp_typescript _tools/manifest.json
  "go.larrymyers.com/protoc-gen-twirp_typescript": "5f59d5a5ab86dd6965a7c8939e60e1927ec55eb2"
```

**Comment by larrymyers** [comment]
@rynop Good catch. The bitbucket mirror has been updated to match GitHub.

Correct. protoc params for args is key=value pairs separated by commas.

**Comment by rynop** [comment]
That worked - thank you!
