### ISSUE TITLE
Generated TS has unused functions

### ISSUE THREAD

**Issue by jonathaningram** [larrymyers/protoc-gen-twirp_typescript#2]
See the simple example in the repo. Look at the `service.ts` file. It has two unused functions:

- `HatToJSON`
- `JSONToSize`

This is because these messages are either an input or an output but not both. Do you have any suggestions for how to solve this? The quickest hack I can think of is to just `export` all of these, but obviously that pollutes the public domain with things you might not need.

Note: this is an issue because when using this generated code in my app, TS complain these are unused and won't compile.

**Comment by jonathaningram** [comment]
Of course, one could use the message for an RPC input and output (would just be uncommon). So I'm thinking that we actually need to be able to check if the message is used and if not, don't output it. Alternatively, I wonder if there's a way to send this through a dead code eliminator relatively easily.

**Comment by larrymyers** [comment]
@jonathaningram it would require some analysis, either at code gen, or after with a static analyzer.

Are you setting the noUnusedLocals in your tsconfig? 

I did a little research and it looks like as of TS 2.6 there is a @ts-ignore directive.

https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-6.html

**Comment by jonathaningram** [comment]
@larrymyers also, yes I was setting `noUnusedLocals` and that's why I'm getting the error but you would see the error in your example prior to my change in #5.
