### ISSUE TITLE
cant go get

### ISSUE THREAD

**Issue by rynop** [larrymyers/protoc-gen-twirp_typescript#20]
Following [docs](https://github.com/larrymyers/protoc-gen-twirp_typescript/blob/master/doc/minimal.md):

```
go get -u go.larrymyers.com/protoc-gen-twirp_typescript
package go.larrymyers.com/protoc-gen-twirp_typescript: unrecognized import path "go.larrymyers.com/protoc-gen-twirp_typescript" (parse https://go.larrymyers.com/protoc-gen-twirp_typescript?go-get=1: no go-import meta tags ())
```

Also tried:

```
go get -u github.com/larrymyers/protoc-gen-twirp_typescript
````

Did you mean to say
```
go get -u github.com/larrymyers/protoc-gen-twirp_typescript/generator/minimal
```

Problem there is it wont get the pbjs right?  sorry, protoc noob here.

**Comment by larrymyers** [comment]
looks like github now considers this a javascript project instead of a go project, which is why the custom import is failing. I have my server setup to filter out non-golang projects.

I'll have to see if github allows explicitly setting the language of a project.

**Comment by rynop** [comment]
While I've never personally done it, I think the answer is `.gitattributes`.  See [this SO](https://stackoverflow.com/questions/34713765/github-changes-repository-to-wrong-language)

**Comment by larrymyers** [comment]
Fixed.

**Comment by rynop** [comment]
Just curious, how did you fix it? I don’t see a commit of gitattributes

**Comment by larrymyers** [comment]
I just pushed the repo to a remote on bitbucket, which does allow you to explicitly set the language, so it gets picked up by my module listing on go.larrymyers.com.
