### ISSUE TITLE
Importing gogoproto causes "twirp.ts: Tried to write the same file twice."

### ISSUE THREAD

**Issue by leeola** [larrymyers/protoc-gen-twirp_typescript#21]
Example proto:

```
syntax = "proto3";
package foo;

import "github.com/gogo/protobuf/gogoproto/gogo.proto";

message Foo {
  string bar = 1;
}
```

Protoc command output:

```
user > protoc -I=$GOPATH/src -I=. --twirp_typescript_out=./foo ./example.proto
twirp.ts: Tried to write the same file twice.
twirp.ts: Tried to write the same file twice.
```

The above proto file is fine before the inclusion of [gogoproto](https://github.com/gogo/protobuf). Once you include the gogoproto import, the Twirp generation breaks.

Thoughts as to why? I'm currently trying to debug this and work past this.

**Comment by leeola** [comment]
Looks like the fix is fairly straight forward. As a quick test, I tried the following change: https://github.com/leeola/protoc-gen-twirp_typescript/commit/608a85ae749c409e20b1147db203c32c6f872f87

Which fixed this one issue at least.

Though, then I ran into other import related problems. I realized that `twirp_typescript` is not outputting files in a directory structure either *(based on proto tree)*, so the directory structure seems broken too. Digging into that still, but for the time being I may try https://github.com/horizon-games/protoc-gen-twirp_ts

**Comment by larrymyers** [comment]
@leeola is this still an issue for you?

**Comment by leeola** [comment]
I'm unsure. I believe I switched away from this lib _(due to other issues)_ and wrote a simplified JSON based typescript generator. I'll close this due to being unable to test it.

**Comment by neRok00** [comment]
This is still an issue for me.

**Comment by marwan-at-work** [comment]
This is an issue for me as well

**Comment by Cyberax** [comment]
This is an issue still

**Comment by larrymyers** [comment]
@neRok00 @marwan-at-work @Cyberax my suggestion would be to use the protobuf.js adapter instead of the JSON based version if your environment can support application/protobuf requests and responses.  Without an active patch for this issue I would not expect any changes soon.
