### ISSUE TITLE
possible to add AuthZ header to fetch?

### ISSUE THREAD

**Issue by rynop** [larrymyers/protoc-gen-twirp_typescript#22]
Is it possible to add headers to the `fetch()`, like [Authorization](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Authorization)? 

Looking at https://github.com/larrymyers/protoc-gen-twirp_typescript/blob/master/generator/minimal/twirp_common.go I don't think there is a way currently.  Want to make sure before I start working on an PR.

My first thought is a 3rd optional param could be passed to the `DefaultXService` factory that specifies options, one of the options being `requestHeaders`.

Ex `main.ts`:
```
import { environment } from '../../environments/environment';
import 'isomorphic-fetch';
import { DefaultShiftsService } from '../shiftcalsapiclient/service';

export { TwirpError } from '../shiftcalsapiclient/twirp';
export * from '../shiftcalsapiclient/service';

export const ShiftService = new DefaultShiftsService(
  environment.apiUrl,
  window.fetch.bind(window),
  {
    requestHeaders: [
        'Authorization': `Bearer ${token}`
    ]
  }
);

```

My guess is https://github.com/larrymyers/protoc-gen-twirp_typescript/issues/10 address this long term, but idea above could be an interim solution.  Thoughts?

**Comment by larrymyers** [comment]
Correct, this is something I recognized on the initial implementation using Fetch.

My immediate suggestion is to use the protobufjs variant of the code generator. I had that use axios instead of Fetch, which is much easier to preconfigure and pass to the proto service.

If you want to have a good at modifying the code gen for the minimal client and submit an PR I'd be happy to review and provide feedback.

**Comment by rynop** [comment]
OK thanks I'll give it a try.

I notice [the generated code](https://github.com/larrymyers/protoc-gen-twirp_typescript/blob/master/example/pbjs_client/service.twirp.ts#L3) uses some un-documented `pbjs-twirp` module of yours.

I'm working on a PR with a few small js/typescript fixes, I'll include the dependency in your [docs](https://github.com/rynop/protoc-gen-twirp_typescript/blob/master/doc/protobufjs.md)

**Comment by rynop** [comment]
I got it working, but have a few comments/questions.

*  How do you debug protobuf request/responses over the wire in chrome?  For problems in the field I'd like to be able to chrome inspect the network tab, and see the request/response payload.  Easy with JSON.  Is there some chrome extension that converts protobuf into human readable for in-field debugging?
*  Just submitted https://github.com/larrymyers/protoc-gen-twirp_typescript/pull/23 for addressing some errors that would not get around TSLint errors
*  Help for others: I use a `google.protobuf.Timestamp` type in my `.proto` file.  To get this working with Typescript (in Angular 6) I had to `yarn add -dT long @types/long` and add `long` to the `types` list in `tsconfig.app.json` Angular file.  See https://github.com/dcodeIO/protobuf.js/issues/940 for root cause.

**Comment by rynop** [comment]
I'm having a heck of a time with the protobufjs variant on mobile.  It's not working, and I can't figure out why because my safari remote debugger keeps crashing.

Performance & size savings for protobuf in the browser [are minimal](https://auth0.com/blog/beating-json-performance-with-protobuf/) AND I'm not keen of being unable to see data over wire from browser.

For these reasons, I'm going to try to tackle making a PR to switch the typescript/minimal generator from fetch to axios.

You don't see any reason against switching do you? Want to make sure you didn't already go down this road before I tackle it.
