### ISSUE TITLE
Imported model can't be found

### ISSUE THREAD

**Issue by JDiPierro** [larrymyers/protoc-gen-twirp_typescript#44]
I have a file `rpc/admin/admin.proto` file with this:

```
import "rpc/identity/identity.proto";

message AccountListResponse {
    repeated GlobalAccount accounts = 1;
}
```

And an `rpc/identity/identity.proto` with this:
```
message GlobalAccount {
    string GUID = 1;
    string Username = 2;
    string PersonaPlatform = 3;
    bool Activated = 4;
    bool EmailOptIn = 5;
    AuthenticationData Authentications = 6;
}
```

When I try to use the typescript generator it complains:
```
retool do protoc --proto_path=. --go_out=paths=source_relative:. --twirp_out=paths=source_relative:. --js_out=import_style=commonjs,binary:. --twirp_typescript_out=. ./rpc/admin/admin.proto
2019/08/13 11:30:07 could not find model of type GlobalAccount for field accounts
--twirp_typescript_out: protoc-gen-twirp_typescript: Plugin failed with status code 1.
retool: fatal err: failed on 'protoc --proto_path=. --go_out=paths=source_relative:. --twirp_out=paths=source_relative:. --js_out=import_style=commonjs,binary:. --twirp_typescript_out=. ./rpc/admin/admin.proto': exit status 1
```

**Comment by larrymyers** [comment]
@JDiPierro If you leave out the twirp_typescript_out arg does it run successfully? If I remember correctly protoc does all the import resolution and just passes the parsed proto spec to the plugin.

**Comment by JDiPierro** [comment]
It does. I switched to [horizon-games/protoc-gen-twirp_ts](https://github.com/horizon-games/protoc-gen-twirp_ts) which is based on your library and it generated successfully. I've run into other problems with that generator :P but it was fine with the imported types.

**Comment by larrymyers** [comment]
Good to hear.  I'll mark this is as a bug and prioritize it.

**Comment by JDiPierro** [comment]
I'm back at this today and got it working!

The original error occurs with the protoc arg `--twirp_typescript_out=.`, but if I use `--twirp_typescript_out=library=pbjs:.` it finds the imported type and outputs successfully.
